---
# default_language_version  :
#   python: python3.11

default_install_hook_types: [commit-msg, pre-commit]

repos                     :
- repo: local
  hooks:
  - id: check-git-msg
    name: check commit msg format
    language: pygrep
    entry: \A(?!(Feature|Bug|Task|Change) (#[0-9 ]+)+- .+)
    stages: [commit-msg]

- repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
  rev: 0.2.3   # or other specific tag
  hooks:
  - id: yamlfmt
    args: [--mapping, '2', --sequence, '2', --offset, '0', --colons, --width, '150']

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0   # Use the ref you want to point at
  hooks:
  - id: trailing-whitespace
    stages: [pre-commit]
  - id: check-merge-conflict
    stages: [pre-commit]
  - id: detect-private-key
    stages: [pre-commit]
  - id: no-commit-to-branch
    stages: [pre-commit]

- repo: https://github.com/asottile/add-trailing-comma
  rev: v3.1.0
  hooks:
  - id: add-trailing-comma
    stages: [pre-commit]

- repo: https://github.com/pre-commit/mirrors-eslint
  rev: v8.56.0
  hooks:
  - id: eslint
    stages: [pre-commit]

- repo: https://github.com/pre-commit/mirrors-prettier
  rev: v3.1.0
  hooks:
  - id: prettier
    stages: [pre-commit]
    types_or: [css, javascript]
