export const en = {
  //Auth labels

  wellCome: 'Welcome back!',
  happyToSeeYouAgain: 'Happy to see you again!',
  companyEmail: 'Company Email',
  gender: 'Gender',
  joiningDate: 'Joining Date',
  onboardingDate: 'Onboarding Date',
  nationality: 'Nationality',

  email: 'Email',
  password: 'Password',
  enterEmailAddress: 'Email address',
  enterPasswordAddress: 'password',
  rememberPassword: 'Remember Password',
  forgotPassword: 'Forgot Password?',
  login: 'Login',
  dontHaveAccount: "Don't have account?",
  registerNow: 'Register Now',
  createYourAccount: 'Create your account!',
  rightReserved: '© 2025 All rights reserved',
  rightReservedDec: 'Product of Softices Consultancy Pvt Ltd',
  forgotPassword: 'Forgot Password',
  forgotDec:
    'Enter your registered email to begin resetting your account password.',
  enterOTPCode: 'Enter OTP Code',
  otp: 'OTP',

  enterOTPCodeDec:
    'Enter a 6-digit code sent to your registered email address. ',
  resetYourPassword: 'Reset Your Password',
  resetPassword: 'Reset Password',
  resetYourPasswordDec:
    'This password should be different form the previous password.',
  confirmPassword: 'Confirm Password',
  didCode: 'Didn’t get a code? ',
  resend: 'resend',
  verify: 'Verify',
  continue: 'Continue',
  companyName: 'Company Name',
  companyMobileNumber: 'Company Mobile Number',

  enter: 'Enter',
  companyAddress: 'Company Address',
  userName: 'User Name',
  alreadyHaveAccount: 'Already have account?',
  loginNow: 'Login Now',
  register: 'Register',

  //Home labels
  dashboard: 'Home',
  termUse: 'Terms of Use',
  privacyPolicy: 'Privacy Policy',

  name: 'Name',
  submit: 'Submit',
  cancel: 'Cancel',
  not_authorized_user: 'You are not authorized user',
  somethingWent: 'Some thing Went wrong',

  // Common
  product: 'Product',
  productPlaceholder: 'Search',
  quantity: 'Quantity',
  quantityPlaceholder: 'Quantity',
  notes: 'Notes',
  notePlaceholder: 'Write note',

  // Add Stock Specific
  addStock: 'Add Stock',
  stocks: 'Stocks',
  production: 'Production',
  productionPlaceholder: 'Select',
  date: 'Date',

  // Add Sale Specific
  addSale: 'Add Sale',
  sales: 'Sales',
  customer: 'Customer',
  customerPlaceholder: 'Search',

  // Filter (shared in both)
  filter: 'Filter',
  filterSubtitle: 'Utilize the provided option to filter the data accordingly.',
  period: 'Period',
  datePlaceholder: 'May 7, 2025',
  clear: 'Clear',
  apply: 'Apply',
  noDataFound: 'No Data Found!',
  noDataFoundDes: 'There is no data to show you right now',

  search: 'Search',

  inProgress: 'In Progress',
  work: 'Work',
  sort: 'Sort',
  productions: 'Productions',
  addProductions: 'Add Productions',
  editProductions: 'Edit Productions',
  productionWorks: 'Production Works',
  contactPerson: 'Contact Person',
  enterName: 'Enter name',
  mobile: 'Mobile',
  enterMobile: 'Enter mobile number',
  whatsApp: 'WhatsApp',
  enterWhatsApp: 'Enter whatsapp number',
  enterEmail: 'Enter email address',

  status: 'Status',
  completedDate: 'Completed Date',
  startedDate: 'Started Date',

  phone: 'Phone',
  finishedAt: 'Finished at',
  update: 'Update',
  updateStatus: 'Update Status',
  customers: 'Customers',
  type: 'Type',
  enterPhoneNumber: 'Enter phone number',
  address: 'Address',
  writeNote: 'Write note',
  photo: 'Photo',
  visitingCard: 'Visiting Card',
  upload: 'Upload',
  addCustomer: 'Add Customer',
  reports: 'Reports',

  pleaseEnterOtp: 'Please enter otp',
  pleaseEnterOTPFull: 'Please enter full OTP of 6 digit',
  day: 'Day',
  hours: 'Hours',
  minutes: 'Minutes',
  seconds: 'Seconds',
  resendIn: 'Resend in ',
  mediaSelectWaring: 'Media Select Waring',
  selectFile: 'Select File',
  chooseFromFiles: 'Choose From Files',
  selectMedia: 'Select Media',
  selectVideo: 'Select Video',
  selectImage: 'Select Image',
  takeVideo: 'Take Video',
  takePhoto: 'Take Photo',
  chooseFromLibrary: 'Choose From Library',
  cancel_cap: 'Cancel',
  changePassword: 'Change Password',
  currentPassword: 'Current Password',
  newPassword: 'New Password',
  confirmNewPassword: 'Confirm New Password',

  inStock: 'In Stock',
  outOfStock: 'Out of Stock',
  active: 'Active',
  addProduct: 'Add Product',
  code: 'Code',
  enterCode: 'Enter code',
  image: 'Image',
  coverImage: 'Cover Image',
  description: 'Description',
  writeDescription: 'Write description',
  view: 'View',
  edit: 'Edit',
  delete: 'Delete',
  products: 'Products',
  deleteConf: 'Are you sure you want to delete ?',
  createdBy: 'Created By',
  tapTheImageToZoomIn: 'Tap the image to zoom in.',
  unit: 'Unit',
  pcs: 'Pcs',
  meter: 'Meter',
  replace: 'Replace',
  order: 'Order',
  all: 'All',
  byNewProduct: 'By New Product',
  byOldProduct: 'By Old Product',
  byName: 'By Name',
  byStatus: 'By Status',
  individual: 'Individual',
  company: 'Company',
  yes: 'Yes',
  no: 'No',

  lastStep: 'Last Step',
  workingTime: 'Working Time',
  timeToFinish: 'Time to finish',
  select: 'Select',

  no: 'No',
  yes: 'Yes',

  minute: 'Minute',
  hour: 'Hour',
  day: 'Day',
  week: 'Week',
  month: 'Month',
  year: 'Year',

  completed: 'Completed',
  cancelled: 'Cancelled',
  changeStatus: 'Change Status',
  logout: 'Logout',
  dateRange: 'Date Range',
  groupBy: 'Group By',

  done: 'Done',
  clear: 'Clear',
  selectRange: 'Select Range',
  editWork: 'Edit Work',
  dateFormate: 'dd - mm - yyyy',
  logoutDesc: 'Are you sure you want to log out?',
  maxUploadDesc: 'You can upload a maximum of 5 images.',
  date: 'Date',
  rsSign: '₹',
  units: 'units',
  items: 'items',

  employee: 'Employee',
  procurement: 'Procurement',
  sale: 'Sale',
  farmer: 'Farmer',
  modules: 'Modules',

  profile: 'Profile',
  basicDetails: 'Basic Details',

  educations: 'Educations',
  families: 'Families',
  heads: 'Heads',
  branch: 'Branch',
  departments: 'Departments',
  designations: 'Designations',
  experiences: 'Experiences',
  degree: 'Degree',
  university: 'University',
  college: 'College',
  specialization: 'Specialization',
  start_year: 'Start year',
  end_year: 'End year',
  pursuing: 'Pursuing',
  responsibilities: 'Responsibilities',
  department: 'Department',
  designation: 'Designation',
  total_working_time_in_month: 'Total working months',
  role: 'Role',
  start_date: 'Start date',
  revoke_date: 'Revoke date',
  holidays: 'Holidays',
  leaves: 'Leaves',
  addLeave: 'Add Leave',
  leaveType: 'Leave Type',
  details: 'Details',
  writeDetails: 'Write Details',

  halfDay: 'Half Day',

  na: 'NA',
};
